name: C++ Projesi Derle

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodlari Cek
      uses: actions/checkout@v4

    - name: JDK Kurulumu (JNI header'lari icin)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: MSBuild Kurulumu
      uses: microsoft/setup-msbuild@v2

    - name: Tum Header Klasorlerini Otomatik Bul ve Tanit
      shell: powershell
      run: |
        $allDirs = Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse -Directory | Select-Object -ExpandProperty FullName
        $jniIncludes = "$env:JAVA_HOME\include;$env:JAVA_HOME\include\win32"
        $includePath = ($allDirs -join ";") + ";$env:GITHUB_WORKSPACE;$jniIncludes"
        Add-Content -Path $env:GITHUB_ENV -Value "INCLUDE=$includePath"
        Add-Content -Path $env:GITHUB_ENV -Value "CL=/std:c++20"

    - name: Visual Studio Projesi Derle (x64)
      run: |
        msbuild dll.sln /p:Configuration=Release /p:Platform=x64 /p:LanguageStandard=stdcpp20

    - name: Doğrudan DLL Olarak Yayınla (Release)
      uses: softprops/action-gh-release@v2
      with:
        files: '**/*.dll'
        tag_name: v1.0.${{ github.run_number }}
        name: 'Surum v1.0.${{ github.run_number }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: DLL Dosyasini Artifact Olarak Yukle
      uses: actions/upload-artifact@v4
      with:
        name: Derlenmis-DLL
        path: '**/*.dll'
