name: C++ Projesi Derle

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodlari Cek
      uses: actions/checkout@v4

    - name: MSBuild Kurulumu
      uses: microsoft/setup-msbuild@v2

    - name: Visual Studio Projesi Derle (.sln)
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64
      continue-on-error: true

    - name: CMake Projesi Derle (CMakeLists.txt)
      run: |
        cmake -B build -A x64
        cmake --build build --config Release
      continue-on-error: true

    - name: DLL Dosyasini Paketle
      uses: actions/upload-artifact@v4
      with:
        name: Derlenmis-DLL
        path: '**/*.dll'
